apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phr-hrd-dep
  name: phr-hrd-svc
  namespace: phr-hrd-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: phr-hrd-dep