apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phr-urd-dep
  name: phr-urd-svc
  namespace: phr-urd-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: phr-urd-dep