apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phr-fro-dep
  name: phr-fro-svc
  namespace: phr-fro-ns
spec:
  ports:
  - port: 2040
    protocol: TCP
    targetPort: 2040
  selector:
    app: phr-fro-dep